import Mirage from 'ember-cli-mirage';

export default Mirage.Factory.extend({
  site(i) { return `Site ${i+1}`; },
  "building": "N/A",
  "room": "N/A",
  "drop": "2.0",
  "rdt": "1.0",
  "rdt-port": "2.0",
  "fdh-port": "2",
  "splitter": "N/A",
  "splitter-fiber": "N/A",
  "pon-card": "N/A",
  "pon-port": "N/A",
  "fdh": "N/A",
  "notes": "N/A",
  "olt-rack": "MDF Rack 6",
  "olt-chassis": "ELOC001",
  "vam-shelf": "N/A",
  "vam-module": "N/A",
  "vam-port": "N/A",
  "backbone-shelf": "N/A",
  "backbone-cable": "N/A",
  "backbone-port": "N/A",
  "fdh-location": "N/A",
  "rdt-location": "N/A",
  "ont-model": "ME4624",
  "ont-sn": "N/A",
  "rdt-port-count": "1-12",
  "ont-ge-1-device": "N/A",
  "ont-ge-1-mac": "N/A",
  "ont-ge-2-device": "N/A",
  "ont-ge-2-mac": "N/A",
  "ont-ge-3-device": "N/A",
  "ont-ge-3-mac": "N/A",
  "ont-ge-4-device": "N/A",
  "ont-ge-4-mac": "N/A"
});
